services:
  db:
    image: postgres:16-alpine
    container_name: app_db
    restart: unless-stopped
    ports:
      - "54388:5432"   # внешний порт НЕ стандартный
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - app_pg_data:/var/lib/postgresql/data

volumes:
  app_pg_data:
